name: ci

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm@v7.5.0
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - run: pnpm recursive install
      - run: pnpm run --recursive compile:dts
      - run: pnpm run --recursive --parallel lint
