name: ci

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up pnpm@v6.23.2
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.2

      - name: Set up node@v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run --recursive --parallel lint
      - run: pnpm run --recursive --parallel typecheck
